# Generated by Django 2.1 on 2018-10-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('displayName', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('srcName', models.CharField(max_length=30)),
            ],
        ),
    ]
