# Generated by Django 2.1 on 2018-10-28 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_auto_20181028_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('displayCat', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('apiCat', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('displayctry', models.CharField(max_length=85, primary_key=True, serialize=False)),
                ('apiCtry', models.CharField(max_length=85)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('displayLang', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('apiLang', models.CharField(max_length=30)),
            ],
        ),
    ]
