# Generated by Django 2.1 on 2018-10-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_category_country_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='factualAccuracy',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='partisanBias',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
