# Generated by Django 2.1 on 2018-10-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_searchhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
